---
- name: Install VMWare Tools
  hosts: RHEL
  tasks:
    - name: Copy TAR file to writable dir
      ansible.builtin.copy:
        src: /path/to/your/vmware-tools.tar.gz
        dest: /tmp/vmware-tools.tar.gz
        owner: root
        group: root
        mode: '0750'
        state: file

    - name: Unpack TAR file
      ansible.builtin.unarchive:
        src: /tmp/vmware-tools.tar.gz
        dest: /tmp/

    - name: Install VMWare tools
      ansible.builtin.command:
        cmd: /tmp/vmware-tools-distrib/vmware-install.pl --default
      become: true
