---
- name: Install VMWare Tools
  hosts: RHEL
  tasks:
    - name: Copy TAR file to writable dir
      ansible.builtin.copy:
        src: /path/to/your/vmware-tools.tar.gz
        dest: /tmp/vmware-tools.tar.gz
        owner: root
        group: root
        mode: '0750'
        state: file

    - name: Unpack TAR file
      ansible.builtin.unarchive:
        src: /tmp/vmware-tools.tar.gz
        dest: /tmp/

    - name: Install VMWare tools
      expect:
        command: /tmp/vmware-tools-distrib/vmware-install.pl
        responses:
          "Accept EULA \\(yes/no\\)": "yes"
          "default \\(yes/no\\)": "yes"
          "Perform USB arbitration \\(yes/no\\)": "no"
          "Do you want to enable Guest Authentication \\(vgauth\\) \\(yes/no\\)": "no"
          "Disable it now \\(yes/no\\)": "no"
          "\\(yes/no\\)": "yes"
        timeout: 300
      become: true

